# Generated by Django 5.2.2 on 2025-06-05 12:53

import surveys.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveylink',
            name='signed_token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='surveylink',
            name='expiry',
            field=models.DateTimeField(default=surveys.models.get_default_expiry),
        ),
        migrations.AlterField(
            model_name='surveylink',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AddIndex(
            model_name='surveylink',
            index=models.Index(fields=['signed_token'], name='surveys_sur_signed__f101f4_idx'),
        ),
    ]
