# Generated by Django 5.2.2 on 2025-06-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveylink_signed_token_alter_surveylink_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='id',
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='response', serialize=False, to='surveys.surveylink'),
        ),
    ]
