# Generated by Django 5.2.2 on 2025-06-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_surveyresponse_id_and_more'),
    ]

    operations = [
    ]
